# Generated by Django 3.0.5 on 2020-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='*', max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
